name: "cd"
on:
  release:
    types: [published]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # deployment steps here...

      - name: Minor Version Bump
        run: |
          git fetch origin develop
          git checkout -b RELEASE/${{github.ref_name}}
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          npm version ${{github.ref_name}} -m "v%s"
          git push --set-upstream origin RELEASE/${{github.ref_name}}
          gh pr create -a @me -B main -t RELEASE/${{github.ref_name}} -b "${{ github.event.release.body }}"
